<?php

namespace Distrifil\CuentaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotaCreditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaCreditoRepository extends EntityRepository
{
}
