<?php

namespace Distrifil\CuentaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotaDebitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaDebitoRepository extends EntityRepository
{
}
